#!/usr/bin/env ansible-playbook
---

- name: provision the chrony
  hosts: all
  vars_files:
    - defaults/main.yml

  tasks:
    - name: include main tasks
      import_tasks: tasks/main.yml

  handlers:
    - name: include handlers
      import_tasks: handlers/main.yml

# vim: ft=ansible :
