#!/usr/bin/env ansible-playbook
---

- name: provision the chrony
  hosts: all
  vars_files:
    - defaults/main.yml

  tasks:
    - name: include tasks
      import_tasks: tasks/main.yml

    - name: check chrony version
      command: chronyc --version
      register: chrony_version
      changed_when: False

    - name: print chrony version
      debug:
        msg: "{{ chrony_version.stdout_lines }}"

  handlers:
    - name: include handlers
      import_tasks: handlers/main.yml

# vim: ft=ansible :
